### ISSUE TITLE
9-2.json 파일 라이브 서버 수정점 공유

### ISSUE THREAD

**Issue by KushKim** [Gyuub/myasset#1]
**9-2.json** "**exam_14_3**"부분 **location** 수정 

> **_기존 1398   ->    수정후 1370_**
<img width="734" alt="image" src="https://user-images.githubusercontent.com/5657393/184758961-eb9f3427-1451-40a2-8a37-3bbb56c93fda.png">

사진은 수정전

**Comment by Gyuub** [comment]
반영완료
